baseurl = "https://pilin.name"

googleAnalytics = "UA-10269049-9"
enableRobotsTXT = true

theme = "hugo-coder"

languagecode = "en"
#defaultcontentlanguage = "en"
#defaultContentLanguageInSubdir = true

paginate = 20

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

#enableGitInfo = true

[params]
    avatarurl = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"

    dateformat = "2 January 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2011

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/ww898/ww898.github.io/commit/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
#    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
#[params.plausibleAnalytics]
#    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
#[params.goatCounter]
#    code = "code"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/ww898/"
#[[params.social]]
#    name = "Gitlab"
#    icon = "fa fa-gitlab"
#    weight = 2
#    url = "https://gitlab.com/ww898/"
#[[params.social]]
#    name = "Bitbucket"
#    icon = "fa fa-bitbucket"
#    weight = 3
#    url = "https://bitbucket.com/ww898/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/ww898/"
[[params.social]]
    name = "Blog"
    icon = "fa fa-pencil"
    weight = 5
    url = "http://workblog.pilin.name/"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 6
    url = "https://www.instagram.com/ww898/"
[[params.social]]
    name = "PGP Key"
    icon = "fa fa-cut-key"
    weight = 7
    url = "https://pilin.name/73519ECF0ACEF7CF.txt"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 8
    url = "https://pilin.name/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "ENG"
        title = "Home"

        [languages.en.params]
            author = "Mikhail Pilin"
            description = "Mikhail Pilin's personal website"
            keywords = "blog,developer,personal"
            info = "Sotfware Architect, Consultant and Engineer"
            footercontent = "Working without regaining consciousness!"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

 #           [[languages.en.menu.main]]
 #           name = "Blog"
 #           weight = 2
 #           url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

 #           [[languages.en.menu.main]]
 #           name = "Contact me"
 #           weight = 5
 #           url = "contact/"

    [languages.ru]
        languagename = "РУС"
        title = "В начало"

        [languages.ru.params]
            author = "Михаил Пилин"
            info = "Архитектор, Консультант и Разработчик пограмного обеспечения"
            description = "Персональный веб-сайт Михаила Пилина"
            keywords = "блог,разработчик,персональный"
            footercontent = "Работаю не приходя в сознание!"

        [languages.ru.menu]

            [[languages.ru.menu.main]]
            name = "Обо мне"
            weight = 1
            url = "about/"

#            [[languages.ru.menu.main]]
#            name = "Блог"
#            weight = 2
#            url = "posts/"

            [[languages.ru.menu.main]]
            name = "Проекты"
            weight = 3
            url = "projects/"

#            [[languages.ru.menu.main]]
#            name = "Контакты"
#            weight = 5
#            url = "contact/"
